name: Local Integration Tests

on: [pull_request, push]

jobs:
  test-local:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Verify Docker Compose
        run: |
          docker --version
          docker compose version
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          chmod +x init-aws.sh
      
      - name: Install AWS CLI and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq curl
          pip install awscli-local
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Start LocalStack environment
        run: ./scripts/start-local.sh
        env:
          TF_INPUT: false
      
      - name: Wait for services to stabilize
        run: sleep 30
      
      - name: Show running containers
        run: docker ps
      
      - name: Verify services are healthy
        run: |
          echo "Checking LocalStack..."
          curl -s http://localhost:4566/_localstack/health || echo "LocalStack not ready"
          
          echo "Checking Elasticsearch..."
          curl -s http://localhost:9200/_cluster/health || echo "Elasticsearch not ready"
          
          echo "Checking Mock SageMaker..."
          curl -s http://localhost:8080/health || echo "Mock SageMaker not ready"
      
      - name: Run integration tests
        run: ./scripts/test-local.sh
      
      - name: View LocalStack logs on failure
        if: failure()
        run: docker compose -f compose.localstack.yml logs localstack
      
      - name: View Elasticsearch logs on failure
        if: failure()
        run: docker compose -f compose.localstack.yml logs elasticsearch
      
      - name: View Mock SageMaker logs on failure
        if: failure()
        run: docker compose -f compose.localstack.yml logs mock-sagemaker
      
      - name: Stop environment
        if: always()
        run: ./scripts/stop-local.sh
