name: Local Integration Tests

on: [pull_request, push]

jobs:
  test-local:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          chmod +x init-aws.sh
      
      - name: Start LocalStack environment
        run: ./scripts/start-local.sh
      
      - name: Wait for services
        run: sleep 30
      
      - name: Run tests
        run: ./scripts/test-local.sh
      
      - name: View logs on failure
        if: failure()
        run: docker-compose -f docker-compose.localstack.yml logs
      
      - name: Stop environment
        if: always()
        run: ./scripts/stop-local.sh
